identifier: mc9el2g0l4r538e3
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: MyWebsite
homeFolder: D:\MyWebsite\My_Website\MyWebsite
distFolder: dist/
outDir: D:\MyWebsite\My_Website\MyWebsite\dist
handle404: ''
allowErrorCollect: true
